[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[metadata]
name = "cli_example"
version = "1.0.0"



[tool.pip]



[tool.pip.dependencies]
pytest = "^6.0"

[tool.pip.dev-dependencies]